version: '3'

services:
  smart-dns-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-dns-proxy
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./logs:/logs
    cap_add:
      - NET_ADMIN
    networks:
      - dns-network

networks:
  dns-network:
    driver: bridge
